name: dart_sandbox
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  riverpod: ^1.0.0-dev.7

dev_dependencies:
  pedantic: ^1.10.0
